# Generated by Django 3.1.3 on 2020-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20201112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialindexpage',
            name='discord_link',
            field=models.CharField(default='http', max_length=350),
        ),
    ]
