# Generated by Django 3.1.3 on 2020-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20201124_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='replLink',
            field=models.CharField(default='http', max_length=350),
        ),
    ]
